version: "3"

services:
  client:
    build: .
    ports:
      - "4200:4200"
  api:
    build: ./api
    ports:
      - "5001:5001"
    environment:
      - DATABASE=mongodb://database/qms
    links:
      - database
    depends_on:
      - database
  database:
    image: mongo
    volumes:
      - qms-data:/data/db"
    ports:
      - "27017:27017"
volumes:
  qms-data:
